import streamlit as st
import cv2
import numpy as np
import librosa
import time
import tempfile
import plotly.graph_objects as go
from PIL import Image
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier

# =========================================================
# 1. THEME & PROJECT BRANDING (BY DHRUV)
# =========================================================
st.set_page_config(
    page_title="DeepScan | Dhruv's Forensic Guard",
    page_icon="🛡️",
    layout="wide"
)

# Professional Custom Styling
st.markdown("""
    <style>
    .main { background-color: #0d1117; color: #c9d1d9; }
    [data-testid="stSidebar"] { background-color: #161b22 !important; border-right: 1px solid #30363d; }
    
    /* Forensic Cards created by Dhruv */
    .dhruv-card {
        background: #1c2128;
        border: 1px solid #444c56;
        border-radius: 12px;
        padding: 22px;
        margin-bottom: 15px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.4);
    }
    
    .status-badge {
        padding: 6px 12px;
        border-radius: 4px;
        font-weight: bold;
        text-transform: uppercase;
    }
    .badge-fake { background-color: #442d30; color: #ff7b72; border: 1px solid #f85149; }
    .badge-real { background-color: #233129; color: #7ee787; border: 1px solid #3fb950; }
    
    /* Scan Animation */
    .scanner { height: 2px; background: #58a6ff; position: relative; animation: move 3s infinite; }
    @keyframes move { 0% { top: 0px; } 50% { top: 200px; } 100% { top: 0px; } }
    </style>
    """, unsafe_allow_html=True)

# =========================================================
# 2. STATE MANAGEMENT
# =========================================================
if 'authenticated' not in st.session_state:
    st.session_state.authenticated = False
if 'audit_logs' not in st.session_state:
    st.session_state.audit_logs = []
if 'analysis_data' not in st.session_state:
    st.session_state.analysis_data = None

# =========================================================
# 3. DHRUV'S FORENSIC ENGINE (ML LOGIC)
# =========================================================
def run_dhruv_engine():
    """Simulates the backend detection process for the demo."""
    time.sleep(2) # Simulating heavy computation
    is_fake = np.random.choice([True, False], p=[0.4, 0.6])
    conf = np.random.uniform(92.4, 99.8)
    
    # Forensic metrics for the Radar Chart
    scores = {
        "Facial Texture": np.random.randint(70, 95) if is_fake else np.random.randint(10, 30),
        "Audio Frequency": np.random.randint(65, 90) if is_fake else np.random.randint(5, 25),
        "Lip-Sync Lag": np.random.randint(60, 99) if is_fake else np.random.randint(0, 15),
        "Blink Consistency": np.random.randint(75, 95) if is_fake else np.random.randint(10, 40),
        "Lighting Noise": np.random.randint(50, 80) if is_fake else np.random.randint(5, 20)
    }
    return is_fake, conf, scores

def create_report_text(name, fake, conf, scores):
    """Generates the downloadable text report."""
    report = f"""
    ==================================================
    FORENSIC AUDIT REPORT: DHRUV'S DEEPFAKE DETECTOR
    ==================================================
    Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    File Inspected: {name}
    Verdict: {'MANIPULATED / FAKE' if fake else 'AUTHENTIC / REAL'}
    Confidence Score: {conf:.2f}%
    
    DETAILED ANALYSIS METRICS:
    --------------------------
    """
    for key, val in scores.items():
        report += f"- {key}: {val}/100 Risk Level\n"
    
    report += "\nFinal Summary:\n"
    if fake:
        report += "The AI detected high-frequency noise in the facial region and a mismatch in the audio-visual synchronization typical of GAN-based generation."
    else:
        report += "The media displays natural biometric signals and consistent light gradients. No synthetic artifacts were found."
    
    report += "\n\nGenerated by: DeepScan (Dhruv's Forensic Guard v4.0)"
    return report

# =========================================================
# 4. PAGE: LOGIN
# =========================================================
def show_login():
    _, col, _ = st.columns([1, 1.5, 1])
    with col:
        st.markdown("<div style='text-align:center; padding-top:100px;'>", unsafe_allow_html=True)
        st.image("https://cdn-icons-png.flaticon.com/512/2092/2092663.png", width=100)
        st.title("Dhruv's Deepfake Detector")
        st.write("Secure Forensic Investigator Access")
        
        with st.form("Login"):
            u = st.text_input("User ID", placeholder="admin")
            p = st.text_input("Access Key", type="password", placeholder="conference2026")
            if st.form_submit_button("Authorize Access"):
                if u == "admin" and p == "conference2026":
                    st.session_state.authenticated = True
                    st.rerun()
                else:
                    st.error("Invalid Credentials.")
        st.markdown("</div>", unsafe_allow_html=True)

# =========================================================
# 5. PAGE: DASHBOARD
# =========================================================
def show_dashboard():
    st.title("🛡️ Dhruv's Forensic Dashboard")
    st.write("Perform deep-level multimodal analysis on suspicious media.")
    st.divider()

    col_up, col_res = st.columns([1.2, 0.8])

    with col_up:
        st.markdown("<div class='dhruv-card'>", unsafe_allow_html=True)
        st.subheader("📁 Upload Media")
        file = st.file_uploader("Select Video/Audio", type=['mp4', 'mov', 'wav', 'avi'])
        if file:
            st.video(file)
            if st.button("⚡ EXECUTE DHRUV'S AUDIT ENGINE"):
                with st.status("Analyzing Data Streams...", expanded=True):
                    st.write("Extracting facial mesh...")
                    time.sleep(1)
                    st.write("Checking audio-visual sync...")
                    time.sleep(1)
                
                is_fake, conf, scores = run_dhruv_engine()
                st.session_state.analysis_data = (is_fake, conf, scores, file.name)
                st.session_state.audit_logs.append({"Time": datetime.now().strftime("%H:%M"), "File": file.name, "Result": "Fake" if is_fake else "Real"})
        st.markdown("</div>", unsafe_allow_html=True)

    with col_res:
        if st.session_state.analysis_data:
            fake, conf, scores, name = st.session_state.analysis_data
            st.markdown("<div class='dhruv-card'>", unsafe_allow_html=True)
            st.subheader("Audit Verdict")
            
            if fake:
                st.markdown("<span class='status-badge badge-fake'>FAKE DETECTED</span>", unsafe_allow_html=True)
                st.error(f"High risk found with {conf:.1f}% confidence.")
            else:
                st.markdown("<span class='status-badge badge-real'>REAL VERIFIED</span>", unsafe_allow_html=True)
                st.success(f"Authentic media verified at {conf:.1f}% confidence.")
            
            # --- DOWNLOAD REPORT FEATURE ---
            report_content = create_report_text(name, fake, conf, scores)
            st.download_button(
                label="📥 Download Forensic Report",
                data=report_content,
                file_name=f"Dhruv_Report_{name}.txt",
                mime="text/plain"
            )
            st.markdown("</div>", unsafe_allow_html=True)

            # Radar Chart
            fig = go.Figure()
            fig.add_trace(go.Scatterpolar(r=list(scores.values()), theta=list(scores.keys()), fill='toself', line_color='#58a6ff'))
            fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 100]), bgcolor="#1c2128"), paper_bgcolor="rgba(0,0,0,0)", font_color="white", height=300, showlegend=False)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Awaiting input for analysis.")

# =========================================================
# 6. OTHER MODULES
# =========================================================
def show_camera():
    st.title("📸 Dhruv's Live Guard")
    c1, c2 = st.columns([1, 1])
    with c1:
        st.markdown("<div class='dhruv-card'>", unsafe_allow_html=True)
        cam = st.camera_input("Scanner")
        if cam:
            st.markdown("<div class='scanner'></div>", unsafe_allow_html=True)
            with st.spinner("Analyzing stream..."):
                time.sleep(2)
                st.success("Stream Authenticated: No deepfake patterns found.")
        st.markdown("</div>", unsafe_allow_html=True)

def show_history():
    st.title("📜 Dhruv's Audit Registry")
    if st.session_state.audit_logs:
        st.table(st.session_state.audit_logs)
    else:
        st.write("No logs available.")

# =========================================================
# MAIN NAVIGATION
# =========================================================
if not st.session_state.authenticated:
    show_login()
else:
    with st.sidebar:
        st.markdown("<h2 style='color:#58a6ff;'>DeepScan AI</h2>", unsafe_allow_html=True)
        st.write("Investigator: **Dhruv**")
        st.divider()
        nav = st.radio("Navigation", ["Dashboard", "Live Camera", "Audit Logs"])
        if st.button("Logout"):
            st.session_state.authenticated = False
            st.rerun()

    if nav == "Dashboard": show_dashboard()
    elif nav == "Live Camera": show_camera()
    elif nav == "Audit Logs": show_history()
